### PR TITLE
Fix automake warnings and compiler warnings

### PR DESCRIPTION
**Pull request by bvanassche**
This patch series fixes the compiler warnings while building eid-mw on my workstation (openSUSE Tumbleweed Linux).

### CODE REVIEW

**Review by yoe — CHANGES_REQUESTED** [review]
I'm fine with the reformat, but the eject_card "test" needs to remain first. It's a workaround for the fact that the machine on which the automated test suite runs (with a robot to eject the card and/or the USB device) sometimes puts the card reader in an unrecoverable sleep, which then causes the full test suite to fail. By ejecting both the card and the reader, we ensure that the reader is definitely not in unrecoverable sleep, and the first test that needs the reader will just insert the card and/or the reader if necessary.

Perhaps add a comment to that effect if you want.

For the other tests, ordering is not significant.

**Review by yoe — CHANGES_REQUESTED** [review]
Apparently commit b24a0588b425a1fea73126dce6c8bdc5b05078c1 accidentally removed the dialogs test, which I think was not the intent. I'd rather re-add it to the TESTS variable than to comment it out.

**Review by yoe — CHANGES_REQUESTED** [review]
Please also drop libbsd from README.md then

**Comment by bvanassche** [comment]
> I'm fine with the reformat, but the eject_card "test" needs to remain first. It's a workaround for the fact that the machine on which the automated test suite runs (with a robot to eject the card and/or the USB device) sometimes puts the card reader in an unrecoverable sleep, which then causes the full test suite to fail. By ejecting both the card and the reader, we ensure that the reader is definitely not in unrecoverable sleep, and the first test that needs the reader will just insert the card and/or the reader if necessary.
> 
> Perhaps add a comment to that effect if you want.
> 
> For the other tests, ordering is not significant.

The eject_card again occurs as the first test and a comment has been added that explains why it occurs first.

**Comment by bvanassche** [comment]
> Apparently commit [b24a058](https://github.com/Fedict/eid-mw/commit/b24a0588b425a1fea73126dce6c8bdc5b05078c1) accidentally removed the dialogs test, which I think was not the intent. I'd rather re-add it to the TESTS variable than to comment it out.

Thanks for the feedback. I have dropped the patch that comments out the directives for the dialog test.

I need help with reenabling that test since it doesn't build.

**Comment by bvanassche** [comment]
> Please also drop libbsd from README.md then

Hmm ... what did I miss? This patch removes the following line from the README: `[libbsd](https://libbsd.freedesktop.org/)`.

**Comment by yoe** [comment]
> > Apparently commit [b24a058](https://github.com/Fedict/eid-mw/commit/b24a0588b425a1fea73126dce6c8bdc5b05078c1) accidentally removed the dialogs test, which I think was not the intent. I'd rather re-add it to the TESTS variable than to comment it out.
> 
> Thanks for the feedback. I have dropped the patch that comments out the directives for the dialog test.
> 
> I need help with reenabling that test since it doesn't build.

Okay, so it turns out it wasn't disabled by accident, it was waiting on build system changes that I meant to do but forgot. That's my job for today :)

Just leave it out of the TESTS variable for now, I'll add it when it builds.

**Comment by yoe** [comment]
> > Please also drop libbsd from README.md then
> 
> Hmm ... what did I miss? This patch removes the following line from the README: `[libbsd](https://libbsd.freedesktop.org/)`.

Nothing, I did. My bad, sorry.

**Pull request merged**
