### PR TITLE
Updates for macOS Catalina and crypto update for macOS

### PR DESCRIPTION
**Pull request by vampirecat35**
Various updates and fixes.
- Updated and fixed for macOS crypto (libcorecrypto)
- Added BEIDViewer app sandboxing
- Updated code to remove deprecations
- Updated everything to support macOS Catalina (10.15)
- Fixed minor code issues

### CODE REVIEW

**Comment by vampirecat35** [comment]
Updates done for macOS Catalina and older to fully support the eID Viewer and BEIDToken app the right way.

**Comment by yoe** [comment]
This just adds an unnecessary version of OpenSSL to the repository without actually compiling it in.

How is this doing things 'the right way'?

What is it you are trying to do?

**Comment by vampirecat35** [comment]
I added this for Mac OS X specifically.
It uses ported Apple code to OpenSSL-1.0.1j (patches from Apple).
I also updated the hashes to corecrypto library (included).
I fixed internet detection so that it doesn't panic when I plug in my eID with internet disabled.
I added sandboxing also and it works.

**Comment by yoe** [comment]
Reopening, as there was no need to close it in the first place.

**Comment by vampirecat35** [comment]
> You had a conflict. That means you have to fix the conflict, not commit the file with the conflict markers.

Gonna reset the branch and add my latest updates.
I switched to 3 types of cipher libraries for Mac OS X EID PKCS11 library.
You can still build with libtomcrypt.
Second option is core crypto (not stable).
Third option is CommonCrypto (stable, from Apple, FIPS compliant).

**Comment by yoe** [comment]
> > You had a conflict. That means you have to fix the conflict, not commit the file with the conflict markers.
> 
> Gonna reset the branch and add my latest updates.

Yes please.

While you're at it please take care to note the following:

- The .xcuserdata files are user-specific settings (window layout of XCode itself, e.g.). These do not belong in git
- .DS_Store files contain folder settings for the macOS finder. These do not belong in git.
- Generated files (such as aclocal.m4 and Makefile.in) may depend on the version of the tool used to generate them, and can break the build if they're used with the wrong version of that tool. These do not belong in git.
- Binary files (.dylib files, e.g.) likewise do not belong in git.

> I switched to 3 types of cipher libraries for Mac OS X EID PKCS11 library.
> You can still build with libtomcrypt.
> Second option is core crypto (not stable).
> Third option is CommonCrypto (stable, from Apple, FIPS compliant).

Please explain why this is beneficial. We currently use the hashing implementations of libtomcrypt because it is self-contained and works on all three platforms. Switching that to other implementations does not provide any tangible benefit that I can see, and so unless you can explain which real-world problem this would solve, we are not going to merge this pull request.

Thanks,

**Comment by yoe** [comment]
This seems to have gone dormant. If you wish to continue this, feel free to reopen. Otherwise, this serves no purpose, so closing for the time being.

Thanks,

**Pull request closed without merging**
