### PR TITLE
Added Visual Studio 2015 Community Edition build

### PR DESCRIPTION
**Pull request by Forceflow**
I added solution and vcprojects files to build the _cardcomm_ modules using the (free) Visual Studio 2015 Community edition, as an alternative to the Visual Studio 2012 toolchain.

I tried respecting and replicating the existing folder structures for VS 2012.

Both projects (_pkcs_ and _minidriver_) compile and work on my system.

### CODE REVIEW

**Comment by Frederikus** [comment]
Hello,
Thank you for your pull request, but we plan to maintain only one buildsystem.
For the 4.1 builds on windows this is still VS 2012.
For the 4.2 builds we'll move over to VS 2015.

**Comment by Forceflow** [comment]
I see - can I commit it to a 4.2 branch then?

**Comment by Frederikus** [comment]
Hello,
You may commit it to the master branch.

**Comment by yoe** [comment]
For clarity: your contribution was welcome, but due to my "normalize line endings" commit, it became cumbersome to merge it anymore. Hence, Frederik did it all over again.

**Pull request closed without merging**
