### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by MarkRijckenberg**
Added link to automated install procedure for Ubuntu 16.04.2 LTS 64-bit

### CODE REVIEW

**Comment by yoe** [comment]
Hi Mark,

As I've already explained on the mailinglist, I'm not convinced this is a very good procedure to install the middleware on Linux. Our eid-mw package *should* do everything that is needed (except for the "apt install eid-mw eid-viewer" step).

Have you tried using that? If so, can you explain to us what failed, and/or what you believe is missing from that procedure? I'm certainly open to improve the official installation in ways that benefit users. However, I'm not convinced that the operations which your script perform do in fact improve upon the official installation procedure; therefore, I'm not going to merge this as-is.

**Comment by MarkRijckenberg** [comment]
Your list of prerequisite packages are incomplete for Ubuntu 16.04.2 64-bit version. I just tested your compile procedure today using a LiveUSB session of Ubuntu 16.04.2 64-bit. The following Archlinux website mentions that libproxy is also a prerequisite which is missing on this Github page. 
https://aur.archlinux.org/packages/eid-mw/
Furthermore, both this Github page and the Archlinux page do not mention several other required dependencies (libssl-dev, libcurl4-openssl-dev, etc....)
So I have updated the procedure to first install the dependencies and packaged version of eid-mw (to pull in other dependencies for eid-mw as well). After installing the precompiled binaries, my bash shell script proceeds with compiling and installing the source code here on Github. I use checkinstall instead of make install to create a binary that overwrites the previous version.... 
Procedure:  https://mark911.wordpress.com/2014/01/04/how-to-get-the-eid-electronic-card-reader-acr38u-working-in-ubuntu-14-04-64-bit/
My installation procedure works using Mozilla Firefox 54.0 in a LiveUSB session or installed version of Ubuntu 16.04.2 64-bit.

**Comment by yoe** [comment]
Hi Mark,

On 08-07-17 11:17, MarkRijckenberg wrote:
> Your list of prerequisite packages are incomplete for Ubuntu 16.04.2
> 64-bit version. I just tested your compile procedure today using a
> LiveUSB session of Ubuntu 16.04.2 64-bit.

Thanks, I did indeed forget to update that after the viewer was merged.
I've now updated the instructions so it should work again.

> The following Archlinux
> website mentions that libproxy is also a prerequisite which is missing
> on this Github page.

That, and a few other things. The list should now be complete again.

[...]

-- 
Wouter Verhelst

**Comment by yoe** [comment]
I think I've addressed the issues you've pointed out. We're not going to point to external documentation (so closing this PR), but further suggestions to improve the current documentation are certainly welcome.

Thanks for your interest,

**Pull request closed without merging**
