### PR TITLE
Fix OpenSSL version check for LibreSSL

### PR DESCRIPTION
**Pull request by cedk**

### CODE REVIEW

**Comment by yoe** [comment]
LGTM. I assume you've actually tested this, and that it works?

**Comment by cedk** [comment]
Yes I compiled and I was able to read my ID card on a machine with only LibreSSL installed.

**Comment by yoe** [comment]
Cool, but the code in question is only used if you hit the "verify" button on the certificates tab... ;-)

**Comment by cedk** [comment]
I click on the "Validate Now" button but nothing happens (and no crash).
I do not know if it means it is working?

**Comment by yoe** [comment]
It should update the certificate icons (but due to a minor bug, that currently only happens if you select another certificate first). If it doesn't crash though, that's good enough for me ;-)

**Comment by cedk** [comment]
OK, I see now when I switch between certificate a green "V" is displayed.

**Comment by yoe** [comment]
Just pushed a commit to master which fixes this minor bug, too ;-)

**Pull request merged**
