### PR TITLE
4 0 7 qt45

### PR DESCRIPTION
**Pull request by mdbeylis**

### CODE REVIEW

**Comment by yoe** [comment]
this makes no sense.

**Comment by Frederikus** [comment]
407 is a very old, no longer supported branch, We are not going to merge it into our master branch

**Comment by mdbeylis** [comment]
Good Day

No sorry this is not what I am wanting to do

I am actaully looking for this code : You can translate almost line by line
https://code.google.com/p/eid-mw/source/browse/trunk/
sdk/Examples/C/src/data.c from C to Delphi.

in this google group :
https://groups.google.com/forum/#!topic/eid-middleware-dev/I-07w68nfIA

**Comment by Frederikus** [comment]
ok, nps,

I see your question was post and answerred on our mailing list (https://groups.google.com/forum/#!forum/eid-middleware-dev), which is the correct place to have these discussions. 
So I think we can close it here.

**Pull request closed without merging**
